name: Checks

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: dmamontov/esphome-lint@main
        with:
          path: "tests"
          use-esphome-compile: true
          esphome-compile-file: "tests/test.yaml"

  lint-branch:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: dmamontov/esphome-lint@main
        with:
          path: "tests"
          esphome-version: "dev"
          use-esphome-branch: true
          use-esphome-compile: true
          esphome-compile-file: "tests/test.yaml"